//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class DHOMA
{
    public int NR_DHOMA { get; set; }
    public string LLOJI { get; set; }
    public int KATI { get; set; }
}

public partial class FATURE
{
    public int FATURE_ID { get; set; }
    public System.DateTime DATA { get; set; }
    public string SHERBIMI_I_OFRUAR { get; set; }
    public int CMIMI_I_SHERBIMIT { get; set; }
    public int TOTALI { get; set; }
    public System.DateTime data_e_leshimit { get; set; }
}

public partial class HOTELI
{
    public string NIPT { get; set; }
    public string EMRI { get; set; }
    public string ADRESA { get; set; }
    public System.DateTime data_e_themelimit { get; set; }
}

public partial class Perdoruesi
{
    public string User_ID { get; set; }
    public string EMRI { get; set; }
    public System.DateTime DATELINDJA { get; set; }
    public string GJINIA { get; set; }
    public string ADRESA { get; set; }
    public string EMAIL { get; set; }
    public string PASSWORD { get; set; }
    public int roli { get; set; }
}

public partial class Rezervimet
{
    public int ID { get; set; }
    public string Emri { get; set; }
    public System.DateTime data_e_rezervimit { get; set; }
    public string periudha { get; set; }
    public int numri_i_personave { get; set; }
}
